# Copyright 2022 MicroEJ Corp. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found with this software.

# All paths must be provided relatively to makefile folder

C_SRCS := 
INC_DIRS := 
DEFINES :=

# Project src/inc files/dirs
##############################

INC_DIRS += \
../platform/inc\
../board/inc\
../freertos/inc\
../lowpower/inc\
../main/inc\
../trace/inc\
../ui/inc\
../util/inc\
../vg/inc\
../thirdparty/systemview/inc\
../thirdparty/systemview-freertos/inc\
../thirdparty/freetype/inc\
../../../sdk/CMSIS/Core/Include\
../../../sdk/CMSIS/DSP/Include\
../../../sdk/devices\
../../../sdk/rtos/freertos/lib/include\
../../../sdk/rtos/freertos/lib/include/private\
../../../sdk/components/ft3267\
../../../sdk/components/video\
../../../sdk/components/video/display\
../../../sdk/components/video/display/dbi\
../../../sdk/components/video/display/dbi/flexio\
../../../sdk/components/video/display/dc/ssd1963\
../../../sdk/components/video/display/dc/lcdif\
../../../sdk/components/video/display/rm68191\
../../../sdk/components/video/display/mipi_dsi_cmd\
../../../sdk/components/video/display/rm68200\
../../../sdk/components/video/display/rm67162\
../../../sdk/components/video/display/dc/dsi_cmd\
../../../sdk/components/video/display/fbdev\
../../../sdk/components/uart\
../../../sdk/components/serial_manager\
../../../sdk/components/lists\
../../../sdk/components/pca9420\
../../../sdk/components/video/display/dc\
../../../sdk/devices/MIMXRT595S\
../../../sdk/devices/MIMXRT595S/drivers\
../../../sdk/devices/MIMXRT595S/utilities/debug_console\
../../../sdk/devices/MIMXRT595S/utilities/str\
../../../sdk/devices/MIMXRT595S/xip\
../../../sdk/middleware/vglite/inc\
../../../sdk/middleware/vglite/VGLiteKernel\
../../../sdk/middleware/vglite/VGLiteKernel/rtos\
../../../sdk/middleware/vglite/VGLite/rtos\
../../../sdk/rtos/amazon-freertos/freertos_kernel/include\
../../../sdk/rtos/amazon-freertos/freertos_kernel/portable/GCC/ARM_CM33_NTZ/non_secure\
../osal/inc\
../platform/inc\
../vglite_support\
../vglite_window\
../thirdparty/harfbuzz/inc\


C_SRCS += \
../board/src/board.c\
../board/src/clock_config.c\
../board/src/display_support.c\
../board/src/pin_mux.c\
../freertos/src/SEGGER_SYSVIEW_Config_FreeRTOS.c\
../lowpower/src/fsl_tickless_rtc.c\
../lowpower/src/power_manager.c\
../simple_gfx_app/src/simple_gfx_app_imp.c\
../main/src/cpuload.c\
../main/src/cpuload_impl_FreeRTOS.c\
../main/src/fault_handlers.c\
../main/src/interrupts.c\
../main/src/LLBSP.c\
../main/src/LLEXT_RES_impl.c\
../main/src/LLMJVM_FreeRTOS.c\
../main/src/main.c\
../main/src/microjvm_main.c\
../main/src/monitor.c\
../main/src/os_support.c\
../main/src/stack_overflow_impl_FreeRTOS.c\
../main/src/time_hardware_timer.c\
../main/src/trace_platform.c\
../osal/src/osal_FreeRTOS.c\
../stub/src/stub.c\
../thirdparty/freetype/src/wrappers/ft_base_wrapper.c\
../thirdparty/freetype/src/wrappers/ft_otf_wrapper.c\
../thirdparty/freetype/src/wrappers/ft_ttf_wrapper.c\
../thirdparty/freetype/src/wrappers/ft_vector_wrapper.c\
../thirdparty/harfbuzz/src/hb-alloc.c\
../thirdparty/systemview/src/SEGGER_RTT.c\
../thirdparty/systemview/src/SEGGER_SYSVIEW.c\
../thirdparty/systemview-freertos/src/SEGGER_SYSVIEW_FreeRTOS.c\
../trace/src/LLMJVM_MONITOR_sysview.c\
../trace/src/LLTRACE_sysview.c\
../ui/src/buttons_helper.c\
../ui/src/buttons_manager.c\
../ui/src/display_dma.c\
../ui/src/display_framebuffer.c\
../ui/src/display_impl.c\
../ui/src/display_utils.c\
../ui/src/display_vglite.c\
../ui/src/drawing_vglite.c\
../ui/src/event_generator.c\
../ui/src/framerate.c\
../ui/src/framerate_impl_FreeRTOS.c\
../ui/src/LLDW_PAINTER_impl.c\
../ui/src/LLUI_DISPLAY_impl.c\
../ui/src/LLUI_INPUT_impl.c\
../ui/src/LLUI_PAINTER_impl.c\
../ui/src/touch_helper.c\
../ui/src/touch_manager.c\
../ui/src/vg_drawer.c\
../ui/src/vglite_path.c\
../util/src/mej_debug.c\
../util/src/mej_math.c\
../util/src/pool.c\
../vg/src/freetype_bitmap_helper.c\
../vg/src/LLVG_BVI_impl.c\
../vg/src/LLVG_FONT_freetype.c\
../vg/src/LLVG_FONT_PAINTER_freetype_bitmap.c\
../vg/src/LLVG_FONT_PAINTER_freetype_vglite.c\
../vg/src/LLVG_FONT_stub.c\
../vg/src/LLVG_GRADIENT_impl.c\
../vg/src/LLVG_impl.c\
../vg/src/LLVG_MATRIX_impl.c\
../vg/src/LLVG_PATH_impl.c\
../vg/src/LLVG_PATH_PAINTER_vglite.c\
../vg/src/LLVG_PATH_stub.c\
../vg/src/LLVG_vglite.c\
../vg/src/microvg_helper.c\
../vglite_support/vglite_support.c\
../vglite_window/vglite_window.c\
../../../sdk/components/lists/fsl_component_generic_list.c\
../../../sdk/components/serial_manager/fsl_component_serial_manager.c\
../../../sdk/components/serial_manager/fsl_component_serial_port_uart.c\
../../../sdk/components/ft3267/fsl_ft3267.c\
../../../sdk/components/pca9420/fsl_pca9420.c\
../../../sdk/components/uart/fsl_adapter_usart.c\
../../../sdk/devices/MIMXRT595S/mcuxpresso/startup_mimxrt595s_cm33.c\
../../../sdk/devices/MIMXRT595S/system_MIMXRT595S_cm33.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_cache.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_clock.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_common.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_common_arm.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_ctimer.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_dma.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_flexcomm.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_flexio.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_flexio_spi.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_flexspi.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_gpio.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_i2c.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_iap.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_inputmux.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_mipi_dsi.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_mipi_dsi_smartdma.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_power.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_powerquad_basic.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_powerquad_cmsis.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_powerquad_data.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_powerquad_filter.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_powerquad_math.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_powerquad_matrix.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_powerquad_transform.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_reset.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_rtc.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_smartdma.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_trng.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_usart.c\
../../../sdk/devices/MIMXRT595S/drivers/fsl_usart_dma.c\
../../../sdk/devices/MIMXRT595S/utilities/fsl_sbrk.c\
../../../sdk/boards/evkmimxrt595/flash_config/flash_config.c\
../../../sdk/rtos/amazon-freertos/freertos_kernel/portable/MemMang/heap_4.c\
../../../sdk/rtos/amazon-freertos/freertos_kernel/portable/GCC/ARM_CM33_NTZ/non_secure/port.c\
../../../sdk/rtos/amazon-freertos/freertos_kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c\
../../../sdk/rtos/amazon-freertos/freertos_kernel/event_groups.c\
../../../sdk/rtos/amazon-freertos/freertos_kernel/list.c\
../../../sdk/rtos/amazon-freertos/freertos_kernel/queue.c\
../../../sdk/rtos/amazon-freertos/freertos_kernel/stream_buffer.c\
../../../sdk/rtos/amazon-freertos/freertos_kernel/tasks.c\
../../../sdk/rtos/amazon-freertos/freertos_kernel/timers.c\
../../../sdk/devices/MIMXRT595S/utilities/fsl_assert.c\
../../../sdk/devices/MIMXRT595S/utilities/debug_console/fsl_debug_console.c\
../../../sdk/devices/MIMXRT595S/utilities/str/fsl_str.c\
../../../sdk/middleware/vglite/VGLite/rtos/vg_lite_os.c\
../../../sdk/middleware/vglite/VGLite/vg_lite.c\
../../../sdk/middleware/vglite/VGLite/vg_lite_image.c\
../../../sdk/middleware/vglite/VGLite/vg_lite_matrix.c\
../../../sdk/middleware/vglite/VGLite/vg_lite_path.c\
../../../sdk/middleware/vglite/VGLiteKernel/rtos/vg_lite_hal.c\
../../../sdk/middleware/vglite/VGLiteKernel/vg_lite_kernel.c\
../../../sdk/components/video/display/dbi/flexio/fsl_dbi_flexio_smartdma.c\
../../../sdk/components/video/display/dc/dsi_cmd/fsl_dc_fb_dsi_cmd.c\
../../../sdk/components/video/display/fbdev/fsl_fbdev.c\
../../../sdk/components/video/display/mipi_dsi_cmd/fsl_mipi_dsi_cmd.c\
../../../sdk/components/video/display/rm67162/fsl_rm67162.c\
../../../sdk/components/video/display/rm68191/fsl_rm68191.c\
../../../sdk/components/video/display/rm68200/fsl_rm68200.c\
../../../sdk/components/video/fsl_video_common.c\

# DEFINES
###########
DEFINES += \
-D__USE_CMSIS\
-DDEBUG\
-DFSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1\
-DBOOT_HEADER_ENABLE=1\
-DCPU_MIMXRT595SFFOB_cm33\
-DBOARD_ENABLE_PSRAM_CACHE=0\
-DFLEXIO_MCULCD_DATA_BUS_WIDTH=8\
-DDBI_FLEXIO_USE_SMARTDMA=1\
-DCUSTOM_VGLITE_MEMORY_CONFIG=1\
-DVG_RESOLVE_ENGINE=0\
-DVG_PE_COLOR_KEY=0\
-DVG_IM_INDEX_FORMAT=0\
-DVG_AYUV_INPUT_OUTPUT=0\
-DVG_DOUBLE_IMAGE=0\
-DVG_RECTANGLE_STRIP_MODE=0\
-DVG_MMU=0\
-DVG_DRIVER_SINGLE_THREAD=1\
-DVG_IM_FILTER=0\
-DVG_IM_YUV_PACKET=1\
-DVG_IM_YUV_PLANAR=0\
-DVG_PE_YUV_PACKET=1\
-DVG_TARGET_TILED=1\
-DVG_COMMAND_CALL=1\
-DVG_SHARE_BUFFER_IM_16K=0\
-DVG_OFFLINE_MODE=0\
-DVG_RESOLUTION_2880=0\
-DVG_PE_PREMULTIPLY=0\
-DVG_POST_CONVERTER=0\
-DVG_PRE_CONVERTER=0\
-DVG_RENDER_BY_MESH=0\
-DVG_TARGET_FAST_CLEAR=0\
-DVG_BUFFER_NUMBER_OF_TARGET=0\
-DVG_VIDEO_CLEAR_CONTROL=0\
-DVG_VIDEO_CONTROL=0\
-DVGLITE_TST_FIRMWARE=0\
-DVG_LITE_SYS_GPU_CTRL=0\
-DSERIAL_PORT_TYPE_UART=1\
-DFSL_RTOS_FREE_RTOS\
-DPRINTF_FLOAT_ENABLE=1\
-DENABLE_SVIEW=1\
-DSDK_I2C_BASED_COMPONENT_USED=1\
-D_VG_LITE_IRQ_CALLBACK=1\
-DSL_WFX_PROD_KEY=1\
-DLWIP_2_1_2\
-DSDK_DEBUGCONSOLE_UART\
-DFT_CONFIG_MODULES_H=\"freetype/config/ftmodule.h\"\
-DFT2_BUILD_LIBRARY\
-DRTT_USE_ASM=0\


# Replaces relative paths by absolute paths
MKFILE_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
MKFILE_DIR := $(dir $(MKFILE_PATH))
C_SRCS := $(foreach file,$(C_SRCS),$(MKFILE_DIR)$(file))
INC_DIRS := $(foreach dir,$(INC_DIRS),-I $(MKFILE_DIR)$(dir))
